import "@/app/assets/css/fontawesome.min.css";
import "@/app/assets/css/style.css";
import "@/app/global.css";
import PathnameWrapper from "./PathnameWrapper";
import AuthProvider from "@/utils/AuthProvider";

export const metadata = {
  title: "কুষ্টিয়া সিটি",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <PathnameWrapper>{children}</PathnameWrapper>
      </AuthProvider>
    </html>
  );
}
