import "@/app/assets/css/fontawesome.min.css";
import "@/app/assets/css/style.css";
import "@/app/global.css";
import PathnameWrapper from "./PathnameWrapper";
import AuthProvider from "@/utils/AuthProvider";

export const metadata = {
  title: "কুষ্টিয়া সিটি",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon-32x32.png",
  },
  openGraph: {
    title: "কুষ্টিয়া সিটি",
    description: "Generated by create next app",
    url: "https://kushtia-city.vercel.app/",
    siteName: "কুষ্টিয়া সিটি",
    images: [
      {
        url: "/main-bg.png",
        width: 1200,
        height: 630,
        alt: "Kushtia City Open Graph Image",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "কুষ্টিয়া সিটি",
    description: "Generated by create next app",
    images: ["/main-bg.png"],
  },
  // manifest: "/site.webmanifest",
  appleWebApp: {
    capable: true,
    title: "কুষ্টিয়া সিটি",
    statusBarStyle: "default",
  },
  viewport: "width=device-width, initial-scale=1",
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "https://kushtia-city.vercel.app/",
  },
  keywords: [
    "কুষ্টিয়া সিটি",
    "Kushtia City",
    "Kushtia",
    "City",
    "Bangladesh",
    "Local Services",
    "Community",
  ],
  authors: [
    {
      name: "SR Dream Lab Team",
      url: "https://kushtia-city.vercel.app/",
    },
  ],
  creator: "SR Dream Lab Team",
  publisher: "SR Dream Lab Team",
  applicationName: "Kushtia City",
  category: "Local Services",
  formatDetection: {
    telephone: false,
  },
  // verification: {
  //   google: "google-site-verification-code",
  //   yandex: "yandex-verification-code",
  //   me: "me-verification-code",
  // },
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>{children}</AuthProvider>
    </html>
  );
}
