import "@/app/global.css";
import "@/app/assets/css/fontawesome.min.css";
import "@/app/assets/css/style.css";

export const metadata = {
  title: "কুষ্টিয়া সিটি",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`home-electrician`}>{children}</body>
    </html>
  );
}
