export const HospitalLinks = [
  {
    serial_no: 1,
    name: "কাসেম্স ক্লিনিক",
    address: "মাহাতাব উদ্দিন সড়ক,কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১২৩",
    registration_date: "২৭-১২-৮৭",
    last_renewal_year: "২০০৫-০৬",
    comments: "কায্যক্রম বন্দ (লাইসেন্স বাতিলের জন্য পত্র প্রেরন করা হয়েছে)।",
  },
  {
    serial_no: 2,
    name: "সার্জিক্যাল ক্লিনিক",
    address: "৪১,মাহাতাব উদ্দিন সড়ক,কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১০৫৪",
    registration_date: "২৭-১--০৪",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 3,
    name: "কুতুব উদ্দিন মেমোরিয়াল হাসপাতাল",
    address: "এম.এম. হোসেন রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১৫৮৬",
    registration_date: "২১-৩-০৭",
    last_renewal_year: "২০০৬-০৭",
    comments: "",
  },
  {
    serial_no: 4,
    name: "আয়েশা ক্লিনিক",
    address: "ঈদগাহ রোড, , কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "৮৮৫",
    registration_date: "১২-১১-০৩",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 5,
    name: "সনো হসপিটাল লিঃ",
    address: "এম.এম. হোসেন রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১৫২৯",
    registration_date: "২৬-০২-০৭",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 6,
    name: "সামসুজ্জামান মেমোরিয়াল হাসপাতাল",
    address: "আর.সি. আর.সি রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১২৯১",
    registration_date: "০৩-৭-০৬",
    last_renewal_year: "২০০৬-০৭",
    comments: "",
  },
  {
    serial_no: 7,
    name: "মরিয়ম ক্লিনিক",
    address: "আর.সি. আর.সি রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "৪৮৯",
    registration_date: "২৩-৯-৯৭",
    last_renewal_year: "২০০৯-১০",
    comments: "",
  },
  {
    serial_no: 8,
    name: "লালনশাহ হাসপাতাল",
    address: "আর.সি. আর.সি রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১৮১৭",
    registration_date: "২৪-৫-০৭",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 8.1,
    name: "ডক্টরস্ ল্যাব প্রাঃ হাসপাতাল",
    address: "আর.সি. আর.সি রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "২২৭১",
    registration_date: "১১-৬-০৯",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 9,
    name: "পদ্বা কমিউনিটি হাসপাতাল",
    address: "আর.সি. আর.সি রোড, কোর্টপাড়া,কুষ্ঠিয়া",
    registration_no: "১৫৯৭",
    registration_date: "২-০৩-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 10,
    name: "আল-কুরনী মেডিকেল সেন্টার",
    address: "দাদাপুর রোড,কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "-",
    comments: "",
  },
  {
    serial_no: 11,
    name: "আদ-দ্বীন হাসপাতাল",
    address: "থানাপাড়া, কুষ্টিয়া",
    registration_no: "৯৩৫",
    registration_date: "২১-১০-১০",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 12,
    name: "নূরুন নাহার জেনারেল হাসপাতাল",
    address: "আর-এ খান চৌদুরীরোড,থানাপাড়া,কুষ্টিয়া",
    registration_no: "৮৮৫",
    registration_date: "২২-১১-০৩",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 13,
    name: "রোটারী আই হাসপাতাল",
    address: "থানাপাড়া, কুষ্টিয়া",
    registration_no: "১৮৯৭",
    registration_date: "০২-৭-০৭",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 14,
    name: "কিরণ পলি ক্লিনিক",
    address: "পলান বক্স রোড ,থানাপাড়া, কুষ্টিয়া",
    registration_no: "",
    registration_date: "-",
    last_renewal_year: "-",
    comments: "",
  },
  {
    serial_no: 15,
    name: "আলো হেল্থ সেন্টার",
    address: "বাবর আলীগেট, আমলাপাড়া ,কুষ্টিয়া",
    registration_no: "১৫৪৪",
    registration_date: "০১-৩-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 16,
    name: "ডাঃ তোফাজ্জুল হেল্থ সেন্টার",
    address: "৪২/১,এন.এস. রোড.কুষ্টিয়া",
    registration_no: "৩৬৪৯",
    registration_date: "২২-৩-০৭",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 17,
    name: "দার-উস-সেফা",
    address: "দাদাপুর রোড,মজমপুর,কষ্টিয়া",
    registration_no: "৭৮",
    registration_date: "২৭-১০-০৪",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 18,
    name: "শাওন ক্লিনিক",
    address: "মজমপুর,কষ্টিয়া",
    registration_no: "৬৮৮",
    registration_date: "১১-০২-০২",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 19,
    name: "আগা ইউসুফ আধুনিক হাসপাতাল",
    address: "বারখাদা,সদর,কুষ্টিয়া",
    registration_no: "৬৩২",
    registration_date: "০৬-৬-০০",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 20,
    name: "ইসলামিয়া হাসপাতাল",
    address: "সদর উপজেলা রোড,কুষ্টিয়া",
    registration_no: "১১১০",
    registration_date: "০১-০৩-৫",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 21,
    name: "কুষ্টিয়া নার্সিং হোম",
    address: "কাষ্টম মোড়,কুষ্টিয়া",
    registration_no: "২০৬৯",
    registration_date: "২৫-১০-০৭",
    last_renewal_year: "২০০৮-০৯",
    comments: "",
  },
  {
    serial_no: 22,
    name: "দিশা আই কেয়ার",
    address: "মজমপুর, কুষ্টিয়া",
    registration_no: "১৮১৩",
    registration_date: "১৫-৫-০৭",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 23,
    name: "মেডিকেয়ার হাসপাতাল",
    address: "চৌড়হাস,সদর,কুষ্টিয়া",
    registration_no: "৫৩৪",
    registration_date: "১০-২-২০০০",
    last_renewal_year: "২০০৭-০৮",
    comments: "",
  },
  {
    serial_no: 23.1,
    name: "বৈশাখী ক্লিনিক",
    address: "আরসিআররি রোড,কোর্টপাড়া,কুষ্টিয়া",
    registration_no: "২৩৪২",
    registration_date: "২৬-০১-০৯",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 24,
    name: "সেবা প্রাইভেট হাসপাতাল",
    address: "হরিনারায়নপুর,সদর,কুষ্টিয়া",
    registration_no: "১৮১৯",
    registration_date: "২৪-৫-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 25,
    name: "নিউসেবা ক্লিনিক",
    address: "হরিনারায়নপুর,সদর,কুষ্টিয়া",
    registration_no: "২০৬২",
    registration_date: "০৯-১০-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 26,
    name: "ঝাউদিয়া ক্লিনিক",
    address: "ঝাউদিয়া বাজার,সদর,কষ্টিয়া",
    registration_no: "২০৬২",
    registration_date: "০৯-১০-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 27,
    name: "নাহার ক্লিনিক",
    address: "পোড়াদহ,মিরপুর,কুষ্টিয়া",
    registration_no: "৬৪৯",
    registration_date: "৩০-৮-০০",
    last_renewal_year: "২০০৭-০৮",
    comments: "",
  },
  {
    serial_no: 28,
    name: "জযমন ক্লিনিক",
    address: "মিরপুর,কুষ্টিয়া",
    registration_no: "১০৮১",
    registration_date: "২৯-১২-০৪",
    last_renewal_year: "২০০৭-০৮",
    comments: "",
  },
  {
    serial_no: 29,
    name: "নাহার নাসিং হোম",
    address: "টি,এন্ট টি রোড,মিরপুর,কুষ্টিয়া",
    registration_no: "১৮১৪",
    registration_date: "২৫-৫-০৭",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 30,
    name: "সোমা ক্লিনিক",
    address: "সেরকান্দি,কুমারখালী,কুষ্টিয়া",
    registration_no: "১৩০৭",
    registration_date: "১৩-৭-০৬",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 31,
    name: "সোহাগ ক্লিনিক",
    address: "কुमারখালী,কুষ্টিয়া",
    registration_no: "১৮৬১",
    registration_date: "১৪-৬-০৭",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 32,
    name: "নোভা ক্লিনিক",
    address: "এলঈীপাড়া,কুমারখালী,কুষ্টিয়া",
    registration_no: "১৮৫৩",
    registration_date: "১১-৬-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 33,
    name: "ফাতেমা ক্লিনिक",
    address: "কুশলীবাসা,কुमারখালী,কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "-",
    comments: "",
  },
  {
    serial_no: 34,
    name: "দৌলতপুর ক্লিনিক",
    address: "হাসপাতাল রোড,দৌলতপুর,কুষ্টিয়া",
    registration_no: "৫০৮",
    registration_date: "২৫-০১-০৭",
    last_renewal_year: "২০০৯-১০",
    comments: "",
  },
  {
    serial_no: 35,
    name: "নিউসেবা ক্লিনিক",
    address: "টিএন্ডটি রোড,দৌলতপুর,কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "২০০৬-০৭",
    comments: "",
  },
  {
    serial_no: 36,
    name: "আলহাজ ক্লিনিক",
    address: "হাসপাতাল রোড,দৌলতপুর,কুষ্টিয়া",
    registration_no: "১৯৯৯",
    registration_date: "০৩-৯-০৭",
    last_renewal_year: "২০০৭-০৮",
    comments: "",
  },
  {
    serial_no: 37,
    name: "মডার্ণ ক্লিনিক",
    address: "হাসপাতাল রোড,দৌলতপুর,কুষ্টিয়া",
    registration_no: "২০০০",
    registration_date: "০৩-৯-০৭",
    last_renewal_year: "২০০৮-০৯",
    comments: "",
  },
  {
    serial_no: 38,
    name: "সুপারসনো হাসপাতাল লিঃ",
    address: "থানা মোড়, ,দৌলতপুর,কুষ্টিয়া",
    registration_no: "১৩৬৫",
    registration_date: "৩১-৮-০৬",
    last_renewal_year: "২০০৮-০৯",
    comments: "",
  },
  {
    serial_no: 39,
    name: "কোহিনুর নাসিং হোম",
    address: "মথুরাপুর, ,দৌলতপুর,কুষ্টিয়া",
    registration_no: "১৩২১",
    registration_date: "০২-৮-০৬",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 40,
    name: "তারাগুনিয়া ক্লিনিক",
    address: "তারাগুনিয়া বাজার, ,দৌলতপুর,কুষ্টিয়া",
    registration_no: "১৮২১",
    registration_date: "২৪-৫-০৭",
    last_renewal_year: "২০০৬-০৭",
    comments: "",
  },
  {
    serial_no: 41,
    name: "জননী নাসিং হোম",
    address: "তারাগুনিয়া বাজার, দৌলতপুর,কুষ্টিয়া",
    registration_no: "১৮৮৮",
    registration_date: "০২-৭-০৭",
    last_renewal_year: "২০০৮-০৯",
    comments: "",
  },
  {
    serial_no: 42,
    name: "হোসেনাবাদ ক্লিনিক",
    address: "হোসেনাবাদ,দৌলতপুর, কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "-",
    comments: "",
  },
  {
    serial_no: 43,
    name: "আরোগ্য সদন",
    address: "ডাংমড়কা,দৌলতপুর,কুষ্টিয়া",
    registration_no: "২১৩০",
    registration_date: "৪-১২-০৭",
    last_renewal_year: "২০০৭-০৮",
    comments: "",
  },
  {
    serial_no: 44,
    name: "আলার দান ক্লিনিক",
    address: "আলার দরগা, কুষ্টিয়া",
    registration_no: "",
    registration_date: "",
    last_renewal_year: "২০০৭-০৮",
    comments: "",
  },
  {
    serial_no: 45,
    name: "মায়ের দোয়া ক্লিনিক",
    address: "আলার দরগা, ,দৌলতপুর,কুষ্টিয়া",
    registration_no: "১৯৭৩",
    registration_date: "",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 46,
    name: "সিটি প্রাঃ হাসপাতাল",
    address: "আলার দরগা, দৌলতপুর,कুষ्टिया",
    registration_no: "১৮২১",
    registration_date: "২৪-৫-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 47,
    name: "সাদিয়া ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "৬০২",
    registration_date: "",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 48,
    name: "ভেড়ামারা নাসিং হোম",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "১০৩০",
    registration_date: "২৪-৮-০৪",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 49,
    name: "আল-হিলাল ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "১৫০৫",
    registration_date: "১৫-০২-০৭",
    last_renewal_year: "২০০৮-০৯",
    comments: "",
  },
  {
    serial_no: 50,
    name: "দরদ ক্লিনিক",
    address: "দক্ষিন রেল গেট,ভেড়ামারা,কুষ্টিয়া",
    registration_no: "১৭৫৩",
    registration_date: "২২-৪-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 51,
    name: "নিরাময় ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "২৭২৪",
    registration_date: "১২-১০-১০",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 52,
    name: "হাসিয়ারা ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "২৭১৬",
    registration_date: "০৪-১০-১০",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 53,
    name: "আমিন স্পেশালাইজড",
    address: "আরসিআরসি রোড,কোর্টপাড়া,কুষ্টিয়া",
    registration_no: "২৪৮২",
    registration_date: "-",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 54,
    name: "এফ.পি.এ.বি ক্লিনিক",
    address: "জেলখানা মোড়,কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "২০০৮-১০",
    comments: "",
  },
  {
    serial_no: 55,
    name: "আলহিরা ক্লিনিক",
    address: "হরিণারায়নপুর,সদর,কুষ্টিয়া",
    registration_no: "২৩৮০",
    registration_date: "১৩-৪-০৯",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 56,
    name: "পান্টি প্রাঃ হাসপাতাল",
    address: "পান্টি বাজার,কুমারখালী,কুষ্টিয়া",
    registration_no: "২৭১৩",
    registration_date: "২৯-৯-১০",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 57,
    name: "মুজিবুর রহমান মেমোরিয়াল হাসপাতাল",
    address: "হাসপাতাল রোড,কুষ্টিয়া",
    registration_no: "২৫৮৮",
    registration_date: "০১-৪-১০",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 58,
    name: "শেখ সিরাজ উদ্দিন ক্লিনিক",
    address: "শালঘরমদুয়া বাজার,কুমারখালী,কুষ্টিয়া",
    registration_no: "২৪২৩",
    registration_date: "২৩-৮-০৯",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 59,
    name: "প্রতিক হাসপাতাল",
    address: "কুমারখালী,কুষ্টিয়া",
    registration_no: "২৫৩০",
    registration_date: "০৭-০২-১০",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 60,
    name: "খোকসা ক্লিনিক",
    address: "খোকসা,কুষ্টিয়া",
    registration_no: "২৩৭৮",
    registration_date: "১৩-৪-০৯",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 61,
    name: "প্রতীক্ষা নাসিং হোম",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "২০০৯-১০",
    comments: "",
  },
  {
    serial_no: 62,
    name: "একতা নার্সিং হোম",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "-",
    registration_date: "-",
    last_renewal_year: "২০০৮-০৯",
    comments: "",
  },
  {
    serial_no: 63,
    name: "শিল্পী ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "১৯৭৫",
    registration_date: "১৯-৮-০৭",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 64,
    name: "মাহমুদা ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "১১৯৭",
    registration_date: "০৪-১১২-৫",
    last_renewal_year: "২০০৯-১০",
    comments: "",
  },
  {
    serial_no: 65,
    name: "শেফা প্রাঃ ক্লিনিক",
    address: "খোকসা,কুষ্টিয়া",
    registration_no: "২৭৯৯",
    registration_date: "৩০-০১-১১",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 66,
    name: "সজীব প্রাঃ হাসপাতাল",
    address: "পোড়াদহ,মিরপুর,কুষ্টিয়া",
    registration_no: "২৮২১",
    registration_date: "০৭-৩-১১",
    last_renewal_year: "২০১০-১১",
    comments: "",
  },
  {
    serial_no: 67,
    name: "দাতা নার্সিং হোম",
    address: "মирপুর,কুষ্টিয়া",
    registration_no: "২৮৮৯",
    registration_date: "১০-৭-১১",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 69,
    name: "ডি সান প্রাঃ হাসপাতাল",
    address: "কোর্টপাড়া,কুষ্টিয়া",
    registration_no: "২৯২৯",
    registration_date: "১৭-৮-১১",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 70,
    name: "বিশ্বাস কমিউনিটি চক্ষু হাসপাতাল",
    address: "কুমারখালী,কুষ্টিয়া",
    registration_no: "২৯৩৪",
    registration_date: "১৭-৮-১১",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
  {
    serial_no: 71,
    name: "আল-নুর ক্লিনিক",
    address: "ভেড়ামারা,কুষ্টিয়া",
    registration_no: "২৭২৩",
    registration_date: "১২-১০-২০১০",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 72,
    name: "আনোয়ারা বিশ্বাস মা ও শিশু হাসপাতাল",
    address: "আলস্নার দরগা,দৌলতপুর,কুষ্টিয়া",
    registration_no: "৩৪২৩",
    registration_date: "১৮-২-১৩",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 73,
    name: "ভিমন কমিউনিটি আই কেয়ার",
    address: "পিচারপতি মোর্শেদ সড়ক,পেয়ারাতলা,কুষ্টিয়া।",
    registration_no: "৩৪২৪",
    registration_date: "১৮-২-১৩",
    last_renewal_year: "২০১২-১৩",
    comments: "",
  },
  {
    serial_no: 74,
    name: "কুমারখালী মডার্ণ হসপিটাল",
    address: "কুমারখালী,কুষ্টিয়া",
    registration_no: "৩১২১",
    registration_date: "০৭-৩-১২",
    last_renewal_year: "২০১১-১২",
    comments: "",
  },
];
